export const APP_ROUTES = {
  landing: "/",
  auth: "/auth",
  quickStart: "/quick-start",
  readAlong: "/read-along",
  goal: "/goal",
  home: "/home",
  myControllables: "/my-controllables",
  train: "/train",
  proof: "/proof",
  proofDex: "/proof/dex",
  dex: "/dex",
  wellness: "/wellness",
  planner: "/planner",
  growth: "/growth",
  reflect: "/reflect",
  wealth: "/wealth",
  money: "/money",
  dashboard: "/dashboard",
  reset: "/reset",
  billing: "/billing",
  admin: "/admin",
  integrations: "/integrations",
} as const;

export const LIFE_OS_ROUTE_PATHS = [
  APP_ROUTES.home,
  APP_ROUTES.readAlong,
  APP_ROUTES.goal,
  APP_ROUTES.myControllables,
  APP_ROUTES.train,
  APP_ROUTES.proof,
  APP_ROUTES.proofDex,
  APP_ROUTES.dex,
  APP_ROUTES.wellness,
  APP_ROUTES.planner,
  APP_ROUTES.growth,
  APP_ROUTES.reflect,
  APP_ROUTES.wealth,
] as const;

export const PRIMARY_ENTRY_ROUTE_PATHS = [
  APP_ROUTES.home,
  APP_ROUTES.train,
  APP_ROUTES.proof,
] as const;
