// Extended Reading Library for Dynamic Daily Readings
// Organized by Controllable and day pattern, drawing from The Controllables book

export type Controllable = 'awareness' | 'perspective' | 'habit' | 'wellness' | 'environment';

export interface Reading {
  id: string;
  controllable: Controllable;
  dayPatterns: number[]; // Days 1-7 this reading is appropriate for
  source: string;
  chapter: string;
  text: string;
  framingLine: string;
  controlLine: string;
  surrenderLine: string;
  questAction: string;
  integrityRep: string;
  reflection: string;
  emoji: string;
}

// Reading pool organized by day pattern:
// Days 1-2: Grounding, awareness, presence
// Days 3-4: Action, small reps, building
// Days 5-6: Perspective, resilience, integration
// Day 7: Reflection, restart, celebration

export const READING_LIBRARY: Reading[] = [
  // ========== AWARENESS READINGS ==========
  {
    id: "awareness_observer_1",
    controllable: "awareness",
    dayPatterns: [1, 2],
    source: "The Controllables",
    chapter: "Chapter 1 – The Dashboard",
    text: "You are not your thoughts. You are the one noticing them.\n\nMost people live inside reactions without ever seeing the controls. Awareness is the moment you realize you have choice.\n\nThis is your Dashboard. Not to control everything, but to see clearly.",
    framingLine: "You Are Here",
    controlLine: "Today, I control my attention.",
    surrenderLine: "Release the need to control everything today. Surrender what you cannot control.",
    questAction: "Pause once today before reacting. Just notice.",
    integrityRep: "Notice one automatic thought without acting on it",
    reflection: "What happens when you pause before reacting?",
    emoji: "👁️",
  },
  {
    id: "awareness_gap_2",
    controllable: "awareness",
    dayPatterns: [1, 2],
    source: "The Controllables",
    chapter: "Chapter 5 – The Space Between",
    text: "Between stimulus and response, there is a gap.\n\nIn that gap lies your power. Your freedom. Your growth.\n\nThe 2-second pause is where you take back the controls. Not to suppress, but to choose.",
    framingLine: "The Gap Is Power",
    controlLine: "Today, I control the space between trigger and response.",
    surrenderLine: "Surrender the impulse to react immediately. Let the pause do its work.",
    questAction: "Before one reaction today, count to two. Then choose.",
    integrityRep: "Practice the 2-second pause in one difficult moment",
    reflection: "What did you notice in the gap?",
    emoji: "⏸️",
  },
  {
    id: "awareness_weather_3",
    controllable: "awareness",
    dayPatterns: [3, 4],
    source: "The Controllables",
    chapter: "Chapter 1 – The Dashboard",
    text: "Name the weather. Don't become it.\n\nThe thought says 'you are anxious.' But are you? Or is anxiety just present?\n\nFeelings are data, not directives. Notice them. Don't obey them blindly.",
    framingLine: "Name It, Don't Become It",
    controlLine: "Today, I control how I relate to my emotions.",
    surrenderLine: "Surrender the need to fix every feeling. Just observe.",
    questAction: "When an emotion arises, say 'There is [emotion] present.'",
    integrityRep: "Name one feeling without trying to change it",
    reflection: "What happens when you observe instead of react?",
    emoji: "🌦️",
  },
  {
    id: "awareness_observe_4",
    controllable: "awareness",
    dayPatterns: [3, 4],
    source: "The Controllables",
    chapter: "Chapter 1 – The Dashboard",
    text: "Observation without judgment is the highest form of intelligence.\n\nThe story in your head is rarely the story that's happening. What you're aware of, you can work with. What you're not aware of, works you.",
    framingLine: "Observe Without Judgment",
    controlLine: "Today, I control my lens of observation.",
    surrenderLine: "Surrender the need to judge every thought. Let them pass.",
    questAction: "Watch your thoughts for 2 minutes without engaging. Just observe.",
    integrityRep: "Catch yourself judging and gently return to observing",
    reflection: "What did you see when you stopped judging?",
    emoji: "🔍",
  },
  {
    id: "awareness_clarity_5",
    controllable: "awareness",
    dayPatterns: [5, 6],
    source: "The Controllables",
    chapter: "Chapter 1 – The Dashboard",
    text: "Clarity comes from observation, not from thinking harder.\n\nReactivity is autopilot. Awareness is taking back the controls.\n\nThe voice in your head is not you. It's just a very talkative roommate.",
    framingLine: "Clarity Through Stillness",
    controlLine: "Today, I control where I direct my awareness.",
    surrenderLine: "Surrender the need to think your way out. Observe your way through.",
    questAction: "Sit quietly for 3 minutes. Notice what arises.",
    integrityRep: "Choose observation over analysis in one situation",
    reflection: "Where did clarity emerge from stillness?",
    emoji: "💎",
  },
  {
    id: "awareness_integrate_6",
    controllable: "awareness",
    dayPatterns: [7],
    source: "The Controllables",
    chapter: "Chapter 1 – The Dashboard",
    text: "Awareness doesn't fix the problem. It shows you where the problem actually is.\n\nYou're not stuck. You just haven't seen the door yet.\n\nThis week, you've practiced seeing. That's the foundation of all change.",
    framingLine: "Seeing Is The Foundation",
    controlLine: "Today, I acknowledge what I've become aware of.",
    surrenderLine: "Surrender the pressure to have all the answers. Seeing is enough.",
    questAction: "Review: What are you now aware of that you weren't before?",
    integrityRep: "Name one insight that emerged from practicing awareness",
    reflection: "How has awareness shifted your experience?",
    emoji: "🦉",
  },

  // ========== PERSPECTIVE READINGS ==========
  {
    id: "perspective_zoom_1",
    controllable: "perspective",
    dayPatterns: [1, 2],
    source: "The Controllables",
    chapter: "Chapter 2 – The Spark of Gratitude",
    text: "Zoom out. How will this matter in a year? In ten?\n\nGratitude is not pretending everything is good. It is remembering what still works.\n\nWhen stress takes over, your world shrinks. Gratitude gently widens it.",
    framingLine: "Widen the View",
    controlLine: "Today, I control my perspective.",
    surrenderLine: "Surrender comparison and resentment. Release what is stealing your peace.",
    questAction: "Name one thing that is still good right now.",
    integrityRep: "Write down three things you're grateful for",
    reflection: "How does gratitude change your view of problems?",
    emoji: "🔭",
  },
  {
    id: "perspective_survived_2",
    controllable: "perspective",
    dayPatterns: [1, 2],
    source: "The Controllables",
    chapter: "Chapter 2 – The Spark of Gratitude",
    text: "You've survived 100% of your hardest days so far.\n\nThis too is temporary. The storm passes. It always does.\n\nPast you handled harder. Future you will handle this.",
    framingLine: "You've Survived Before",
    controlLine: "Today, I control how I remember my resilience.",
    surrenderLine: "Surrender the fear that this is permanent. It never is.",
    questAction: "List one hard thing you survived. What did you learn?",
    integrityRep: "Remind yourself of a past victory when doubt arises",
    reflection: "What does your track record tell you about today?",
    emoji: "🛡️",
  },
  {
    id: "perspective_turtle_3",
    controllable: "perspective",
    dayPatterns: [3, 4],
    source: "The Controllables",
    chapter: "Chapter 2 – The Spark of Gratitude",
    text: "The turtle doesn't compare itself to the rabbit. It just keeps moving.\n\nPatience is perspective in motion. Slow is smooth, smooth is fast.\n\nEvery expert was once a beginner who didn't quit.",
    framingLine: "The Turtle Wisdom",
    controlLine: "Today, I control my pace without comparison.",
    surrenderLine: "Surrender the urge to rush. Release comparison to others.",
    questAction: "Move at your pace today. Don't compare to anyone else.",
    integrityRep: "When tempted to compare, remember the turtle",
    reflection: "What happens when you stop competing?",
    emoji: "🐢",
  },
  {
    id: "perspective_10years_4",
    controllable: "perspective",
    dayPatterns: [3, 4],
    source: "The Controllables",
    chapter: "Chapter 2 – The Spark of Gratitude",
    text: "Today's crisis is tomorrow's story. How do you want to tell it?\n\nThe obstacle in front of you looks smaller from 30,000 feet.\n\nUrgency is often just poor perspective. Slow down. Think longer.",
    framingLine: "The 30,000 Foot View",
    controlLine: "Today, I control the altitude of my thinking.",
    surrenderLine: "Surrender the false urgency. Take the longer view.",
    questAction: "Ask: How will this matter in 10 years?",
    integrityRep: "Zoom out before making one decision today",
    reflection: "What changes when you think in decades?",
    emoji: "✈️",
  },
  {
    id: "perspective_story_5",
    controllable: "perspective",
    dayPatterns: [5, 6],
    source: "The Controllables",
    chapter: "Chapter 2 – The Spark of Gratitude",
    text: "In the story of your life, this chapter isn't the whole book.\n\nHard times create strong foundations. You're being forged, not broken.\n\nWhat feels like the end is often just the middle.",
    framingLine: "This Is Just A Chapter",
    controlLine: "Today, I control the narrative I tell myself.",
    surrenderLine: "Surrender the belief that this moment defines you. It's just a page.",
    questAction: "Rewrite today's challenge as the start of a triumph.",
    integrityRep: "Tell the story differently in your mind",
    reflection: "How does changing the narrative change the feeling?",
    emoji: "📖",
  },
  {
    id: "perspective_integrate_6",
    controllable: "perspective",
    dayPatterns: [7],
    source: "The Controllables",
    chapter: "Chapter 2 – The Spark of Gratitude",
    text: "A year from now, you'll wish you'd started today. But today is here.\n\nThe view from the summit always makes the climb worth it.\n\nSlow progress is still progress. The turtle finishes the race.",
    framingLine: "Progress Is Perspective",
    controlLine: "Today, I acknowledge how far I've come.",
    surrenderLine: "Surrender the need for instant results. Trust the process.",
    questAction: "Look back at Day 1. What shifted in your perspective?",
    integrityRep: "Name one way your perspective expanded this week",
    reflection: "What will you remember about this week's view?",
    emoji: "🔭",
  },

  // ========== HABIT READINGS ==========
  {
    id: "habit_rep_1",
    controllable: "habit",
    dayPatterns: [1, 2],
    source: "The Controllables",
    chapter: "Chapter 4 – The Symphony of Positive Choices",
    text: "You don't need a perfect plan. You need one repeatable action.\n\nSmall actions, done consistently, reshape your system. One rep keeps momentum alive.\n\nThis is how habits form. Quietly. Over time.",
    framingLine: "One Rep Is Enough",
    controlLine: "Today, I control whether I start.",
    surrenderLine: "Surrender perfection. Release the pressure to do more than today requires.",
    questAction: "Complete one small rep aligned with your quest.",
    integrityRep: "Do one rep—no matter how small",
    reflection: "What if consistency mattered more than intensity?",
    emoji: "🦈",
  },
  {
    id: "habit_shark_2",
    controllable: "habit",
    dayPatterns: [1, 2],
    source: "The Controllables",
    chapter: "Chapter 4 – The Symphony of Positive Choices",
    text: "The shark doesn't ask if it feels like swimming. It swims.\n\nReps beat motivation. Every time.\n\nYou level up through reps, not talent.",
    framingLine: "The Shark Just Swims",
    controlLine: "Today, I control whether I do the rep.",
    surrenderLine: "Surrender the need to feel motivated. Just start.",
    questAction: "Do the rep before you feel ready.",
    integrityRep: "Start something without waiting for motivation",
    reflection: "What if you didn't need to feel like it?",
    emoji: "🦈",
  },
  {
    id: "habit_2min_3",
    controllable: "habit",
    dayPatterns: [3, 4],
    source: "The Controllables",
    chapter: "Chapter 4 – The Symphony of Positive Choices",
    text: "Two minutes. That's all you need. Start with two minutes.\n\nThe smallest action beats the grandest intention.\n\nIdentity is just repeated action. Change the rep, change the person.",
    framingLine: "Two Minutes Is Enough",
    controlLine: "Today, I control the start, not the finish.",
    surrenderLine: "Surrender the all-or-nothing mindset. Two minutes counts.",
    questAction: "Shrink your task to 2 minutes. Then do it.",
    integrityRep: "Complete a 2-minute version of something you've been avoiding",
    reflection: "What opened up when you just started?",
    emoji: "⏱️",
  },
  {
    id: "habit_identity_4",
    controllable: "habit",
    dayPatterns: [3, 4],
    source: "The Controllables",
    chapter: "Chapter 4 – The Symphony of Positive Choices",
    text: "The question isn't 'Do I feel like it?' The question is 'Who do I want to become?'\n\nYour future self is built by today's reps, not today's plans.\n\nConsistency compounds. One day you'll look up and realize you've leveled up.",
    framingLine: "Become Who You Practice Being",
    controlLine: "Today, I control who I'm becoming through action.",
    surrenderLine: "Surrender the old identity. Let the reps build the new one.",
    questAction: "Ask: What would the person I want to become do right now?",
    integrityRep: "Act as the person you're becoming, not the person you were",
    reflection: "What identity are your reps building?",
    emoji: "🔄",
  },
  {
    id: "habit_never_zero_5",
    controllable: "habit",
    dayPatterns: [5, 6],
    source: "The Controllables",
    chapter: "Chapter 4 – The Symphony of Positive Choices",
    text: "Never zero. On your worst day, do one rep. Keep the streak alive.\n\nMiss one rep, you're human. Miss two, you're building a new habit.\n\nShow up sloppy. Sloppy still counts. Perfect and absent counts for nothing.",
    framingLine: "Never Zero",
    controlLine: "Today, I control showing up, not being perfect.",
    surrenderLine: "Surrender the need to be great. Just don't be absent.",
    questAction: "Even if today is hard, do one tiny rep.",
    integrityRep: "On a difficult day, do the absolute minimum—but do it",
    reflection: "What's your 'never zero' version?",
    emoji: "1️⃣",
  },
  {
    id: "habit_integrate_6",
    controllable: "habit",
    dayPatterns: [7],
    source: "The Controllables",
    chapter: "Chapter 4 – The Symphony of Positive Choices",
    text: "The rep doesn't need to be good. It needs to happen.\n\nMotivation gets you started. Habits keep you going.\n\nThis week you practiced showing up. That's the foundation of everything.",
    framingLine: "Showing Up Is The Work",
    controlLine: "Today, I acknowledge the reps I completed.",
    surrenderLine: "Surrender the judgment of your reps. Showing up was the goal.",
    questAction: "Count your reps this week. Celebrate the pattern.",
    integrityRep: "Acknowledge one habit you strengthened",
    reflection: "What's easier now than it was on Day 1?",
    emoji: "🦈",
  },

  // ========== WELLNESS READINGS ==========
  {
    id: "wellness_systems_1",
    controllable: "wellness",
    dayPatterns: [1, 2],
    source: "The Controllables",
    chapter: "Chapter 7 – The Systems Check",
    text: "Before you diagnose yourself with depression, check your sleep, water, and movement.\n\nYour body keeps score. What's the current tally?\n\nThe basics are basic because they work.",
    framingLine: "Check Your Systems",
    controlLine: "Today, I control the basics that keep me running.",
    surrenderLine: "Surrender the complicated. Return to the simple.",
    questAction: "Rate 1-5: Sleep, Food, Water, Movement. Fix the lowest.",
    integrityRep: "Address one neglected basic today",
    reflection: "Which system needed attention most?",
    emoji: "🛰️",
  },
  {
    id: "wellness_rest_2",
    controllable: "wellness",
    dayPatterns: [1, 2],
    source: "The Controllables",
    chapter: "Chapter 7 – The Systems Check",
    text: "Rest is not weakness. It's maintenance.\n\nSleep is not negotiable. It's the foundation everything else is built on.\n\nRecovery is part of the work. Not a break from the work.",
    framingLine: "Rest Is Maintenance",
    controlLine: "Today, I control how I recover.",
    surrenderLine: "Surrender the guilt of resting. It's essential, not optional.",
    questAction: "Prioritize one form of rest today. Honor it.",
    integrityRep: "Rest without guilt for at least 10 minutes",
    reflection: "What happens when you let yourself recover?",
    emoji: "😴",
  },
  {
    id: "wellness_fuel_3",
    controllable: "wellness",
    dayPatterns: [3, 4],
    source: "The Controllables",
    chapter: "Chapter 7 – The Systems Check",
    text: "Output is limited by input. What's your fuel?\n\nThe brain runs on the body. Fuel the body right.\n\nWater. Seriously. Start there.",
    framingLine: "Fuel Matters",
    controlLine: "Today, I control what I put into my body.",
    surrenderLine: "Surrender the shortcuts. Fuel affects everything.",
    questAction: "Drink 3 glasses of water before noon.",
    integrityRep: "Choose fuel over convenience in one meal",
    reflection: "How does better fuel change your day?",
    emoji: "💧",
  },
  {
    id: "wellness_movement_4",
    controllable: "wellness",
    dayPatterns: [3, 4],
    source: "The Controllables",
    chapter: "Chapter 7 – The Systems Check",
    text: "Movement is medicine. Not punishment—medicine.\n\nYour body is the vehicle. Take care of the engine.\n\nTired, hungry, or dehydrated? Fix those first. Everything else can wait.",
    framingLine: "Movement As Medicine",
    controlLine: "Today, I control whether I move.",
    surrenderLine: "Surrender the all-or-nothing. Any movement counts.",
    questAction: "Move for 5 minutes today. Walk, stretch, dance. Anything.",
    integrityRep: "Choose movement over stillness once today",
    reflection: "How did your body feel after moving?",
    emoji: "🏃",
  },
  {
    id: "wellness_signals_5",
    controllable: "wellness",
    dayPatterns: [5, 6],
    source: "The Controllables",
    chapter: "Chapter 7 – The Systems Check",
    text: "Low energy isn't a character flaw. It's a signal.\n\nThe satellite monitors all systems. Right now, which one is in the red?\n\nYour nervous system keeps receipts. Stress compounds. So does rest.",
    framingLine: "Listen To The Signals",
    controlLine: "Today, I control how I respond to my body's signals.",
    surrenderLine: "Surrender ignoring the warning lights. They're there for a reason.",
    questAction: "Identify one signal your body is sending. Honor it.",
    integrityRep: "Respond to a body signal instead of pushing through",
    reflection: "What is your body trying to tell you?",
    emoji: "📡",
  },
  {
    id: "wellness_integrate_6",
    controllable: "wellness",
    dayPatterns: [7],
    source: "The Controllables",
    chapter: "Chapter 7 – The Systems Check",
    text: "Wellness isn't spa days. It's consistent maintenance.\n\nOne good night of sleep can change your entire perspective.\n\nThe systems that keep you alive deserve attention.",
    framingLine: "Maintenance Is The Practice",
    controlLine: "Today, I acknowledge the systems I maintained.",
    surrenderLine: "Surrender the need for perfection. Maintenance is enough.",
    questAction: "Review: Which wellness system improved this week?",
    integrityRep: "Name one way you took better care of yourself",
    reflection: "How did attending to wellness change your week?",
    emoji: "🛰️",
  },

  // ========== ENVIRONMENT READINGS ==========
  {
    id: "environment_design_1",
    controllable: "environment",
    dayPatterns: [1, 2],
    source: "The Controllables",
    chapter: "Chapter 8 – Environment Design",
    text: "Environment beats willpower. Every time.\n\nYour environment is either supporting your goals or sabotaging them. There is no neutral.\n\nThe rocket doesn't fight gravity—it uses physics. You can use environment the same way.",
    framingLine: "Design Beats Discipline",
    controlLine: "Today, I control one element of my environment.",
    surrenderLine: "Surrender the belief that willpower alone will work. Design helps.",
    questAction: "Change one thing in your environment to support your goal.",
    integrityRep: "Remove or add one physical cue in your space",
    reflection: "What changed when your environment changed?",
    emoji: "🚀",
  },
  {
    id: "environment_friction_2",
    controllable: "environment",
    dayPatterns: [1, 2],
    source: "The Controllables",
    chapter: "Chapter 8 – Environment Design",
    text: "Remove friction from good choices. Add friction to bad ones.\n\nIf you have to think about it, you probably won't do it. Make the default the goal.\n\nThe easiest path is the path you'll take. Engineer the easy path.",
    framingLine: "Friction Is Strategy",
    controlLine: "Today, I control the friction in my environment.",
    surrenderLine: "Surrender relying on discipline. Use design instead.",
    questAction: "Make one good thing easier. Make one bad thing harder.",
    integrityRep: "Add or remove friction for one behavior",
    reflection: "How did changing friction change behavior?",
    emoji: "🔧",
  },
  {
    id: "environment_defaults_3",
    controllable: "environment",
    dayPatterns: [3, 4],
    source: "The Controllables",
    chapter: "Chapter 8 – Environment Design",
    text: "You don't need more discipline. You need better defaults.\n\nWhat's visible is what gets done. Put the right things in view.\n\nStop relying on willpower. Redesign the system.",
    framingLine: "Better Defaults",
    controlLine: "Today, I control what my defaults are set to.",
    surrenderLine: "Surrender the old defaults. Set new ones intentionally.",
    questAction: "Change one default in your day. Set it up tonight for tomorrow.",
    integrityRep: "Redesign one default to support your goal",
    reflection: "What default needed to change most?",
    emoji: "⚙️",
  },
  {
    id: "environment_inputs_4",
    controllable: "environment",
    dayPatterns: [3, 4],
    source: "The Controllables",
    chapter: "Chapter 8 – Environment Design",
    text: "You are the average of your five closest inputs. Choose wisely.\n\nChange the inputs, change the outputs. It's that simple.\n\nEvery environment is designed. The question is: by whom, and for what?",
    framingLine: "Audit Your Inputs",
    controlLine: "Today, I control what I let into my mind.",
    surrenderLine: "Surrender inputs that drain you. Make room for better ones.",
    questAction: "List your 5 most common inputs. Is each one serving you?",
    integrityRep: "Remove or reduce one negative input today",
    reflection: "Which input needed to go?",
    emoji: "📥",
  },
  {
    id: "environment_future_5",
    controllable: "environment",
    dayPatterns: [5, 6],
    source: "The Controllables",
    chapter: "Chapter 8 – Environment Design",
    text: "Design your environment for your future self, not your current feelings.\n\nYour future self needs a runway, not a wall. Build the runway.\n\nEnvironment design is kindness to your future self.",
    framingLine: "Build For Future You",
    controlLine: "Today, I control what I set up for tomorrow.",
    surrenderLine: "Surrender the short-term comfort. Build for the long game.",
    questAction: "Set up one thing tonight that will help tomorrow you.",
    integrityRep: "Do a favor for your future self today",
    reflection: "How did your past self set you up for today?",
    emoji: "🎁",
  },
  {
    id: "environment_integrate_6",
    controllable: "environment",
    dayPatterns: [7],
    source: "The Controllables",
    chapter: "Chapter 8 – Environment Design",
    text: "Your environment is a choice you make once that pays dividends forever.\n\nWillpower is a battery. Environment is solar power. Build for solar.\n\nThis week you learned: blame the system before you blame yourself. Then fix the system.",
    framingLine: "Systems Over Willpower",
    controlLine: "Today, I acknowledge the environmental changes I made.",
    surrenderLine: "Surrender self-blame. The system was the problem, not you.",
    questAction: "Review: What environmental change had the biggest impact?",
    integrityRep: "Name one system improvement you'll keep",
    reflection: "What will you design differently going forward?",
    emoji: "🚀",
  },

  // ========== INTEGRATION/RESTART READINGS ==========
  {
    id: "integration_restart_1",
    controllable: "awareness",
    dayPatterns: [7],
    source: "The Controllables",
    chapter: "Chapter 9 – The Continuous Upgrade",
    text: "Starting over is not failure. It's a skill.\n\nThe best restarters aren't the ones who never fall—they're the ones who get back up the fastest.\n\nEvery day is Day 1 if you choose it.",
    framingLine: "You Know How To Restart",
    controlLine: "Today, I control my re-entry.",
    surrenderLine: "Surrender fear of falling off again. Release control over the outcome.",
    questAction: "Acknowledge what changed. Decide one next step.",
    integrityRep: "Write down your restart protocol",
    reflection: "What will you do differently next time you fall off?",
    emoji: "🔄",
  },
  {
    id: "integration_record_2",
    controllable: "perspective",
    dayPatterns: [7],
    source: "The Controllables",
    chapter: "Chapter 9 – The Continuous Upgrade",
    text: "The record of effort matters more than the streak.\n\nThis week was not about perfection. It was about re-entry.\n\nYou noticed. You chose. You adjusted. That means you know how to come back.",
    framingLine: "The Record Matters",
    controlLine: "Today, I acknowledge my record of effort.",
    surrenderLine: "Surrender the streak obsession. The effort is what counts.",
    questAction: "Review your week. What's the record of effort?",
    integrityRep: "Celebrate showing up, not the outcome",
    reflection: "What does your record of effort prove?",
    emoji: "📝",
  },
  {
    id: "integration_return_3",
    controllable: "habit",
    dayPatterns: [7],
    source: "The Controllables",
    chapter: "Chapter 9 – The Continuous Upgrade",
    text: "Life will pull you off track again. That's normal.\n\nThe win is knowing how to reset without shame.\n\nYou don't need to be motivated. You need to be consistent. And you were.",
    framingLine: "Returning Is The Practice",
    controlLine: "Today, I commit to returning when I fall.",
    surrenderLine: "Surrender the shame of falling. It's part of the path.",
    questAction: "Name one moment you returned this week instead of giving up.",
    integrityRep: "Commit to one thing you'll return to when you fall next",
    reflection: "What made you come back?",
    emoji: "🔁",
  },
];

/**
 * Get a rotated day's reading based on controllable focus and snapshot count
 * @param dayNumber - Day 1-7 of the snapshot
 * @param controllable - The focus controllable for this snapshot
 * @param snapshotCount - How many snapshots the user has completed (for rotation)
 */
export function getRotatedReading(
  dayNumber: number,
  controllable: Controllable,
  snapshotCount: number = 0
): Reading {
  // Filter readings appropriate for this day pattern
  const dayAppropriateReadings = READING_LIBRARY.filter(
    r => r.dayPatterns.includes(dayNumber)
  );

  // Filter by controllable first
  let matchingReadings = dayAppropriateReadings.filter(
    r => r.controllable === controllable
  );

  // If no exact match, fall back to any reading for this day pattern
  if (matchingReadings.length === 0) {
    matchingReadings = dayAppropriateReadings;
  }

  // Use snapshot count to rotate through available readings
  const rotationIndex = snapshotCount % matchingReadings.length;
  return matchingReadings[rotationIndex] || READING_LIBRARY[0];
}

/**
 * Get day content with rotation - replaces static getDayContent
 */
export function getRotatedDayContent(
  dayNumber: number,
  controllable: Controllable | string,
  snapshotCount: number = 0
) {
  const normalizedControllable = controllable.toLowerCase() as Controllable;
  const reading = getRotatedReading(dayNumber, normalizedControllable, snapshotCount);

  return {
    day: dayNumber,
    controllable: reading.controllable.charAt(0).toUpperCase() + reading.controllable.slice(1),
    emoji: reading.emoji,
    framingLine: reading.framingLine,
    prompt: reading.reflection,
    inputType: "text" as const,
    completionButtonText: "Complete Day " + dayNumber,
    surrenderLine: reading.surrenderLine,
    controlLine: reading.controlLine,
    questAction: reading.questAction,
    integrityRep: reading.integrityRep,
    reflection: reading.reflection,
    reading: {
      source: reading.source,
      chapter: reading.chapter,
      text: reading.text,
    },
  };
}
